import LayoutWrapper from "@/utils/LayoutWrapper";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: {
    default: "Business inventory management system",
    template: "%s - Business IMS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <LayoutWrapper>
          <Toaster position="top-right" />
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
